spring:
  thymeleaf:
    cache: false    #关闭缓存
    mode: LEGACYHTML5


pagehelper:
  helper-dialect: mysql    #设置数据库方言
  #分页合理化参数，默认值为 false，默认 false 时，直接根据参数进行查询。
  #当该参数设置为 true 时，pageNum<=0 时会查询第一页，pageNum>pages（超过总数时），会查询最后一页。
  reasonable: true
  #支持通过 Mapper 接口参数来传递分页参数，默认值false 。
  #分页插件会从查询方法的参数值中，自动根据上面 params 配置的字段中取值，查找到合适的值时就会自动分页。
  support-methods-arguments: true
  #
  params: count=countSql