spring:
  application:
    name: zhs-common    # 服务名称

server:
  port: 9200    # 端口号


eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10    # 表示eureka client发送心跳给server端的频率，默认30秒
    health-check-url-path: /actuator/health
    metadata-map:
      startup: "hello zhs"    #needed to trigger info and endpoint update after restart
  client:
    registryFetchIntervalSeconds: 5    # 表示eureka client间隔多久去拉取服务注册信息，默认为30秒
    service-url:
      defaultZone: http://localhost:9000/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

logging:
  file: log/zhs-common/my.log


info:
  tags:
    environment: dev
  version: @project.version@
  groupId: @project.groupId@
  artifactId: @project.artifactId@