# 说明文档
# http://codecentric.github.io/spring-boot-admin/2.1.5/

spring:
  application:
    name: zhs-monitor    # 服务名称

server:
  port: 9100    # 端口号

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka/
  instance:
    status-page-url-path: /    # 从 eureka 服务列表页面直接点击 zhs-monitor 服务时，直接可进去服务监控页面


info:
  environment: dev
  description: 服务监控
  version: @project.version@
  groupId: @project.groupId@
  artifactId: @project.artifactId@
